#ifndef _TANK_SPRITE_H_
#define _TANK_SPRITE_H_
#include "config.h"

// 16x16 tile sprites as BGRA uint32 arrays
// Each sprite: 256 pixels, row-major order

// === BRICK WALL ===
// Brown bricks with darker mortar, offset pattern
static const UINT32 sprBrick[256] = {
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,
  COLOR_DKBROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_DKBROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_DKBROWN,
  COLOR_DKBROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_DKBROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_DKBROWN,
  COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,
  COLOR_DKBROWN,COLOR_BROWN,COLOR_BROWN,COLOR_DKBROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_DKBROWN,COLOR_BROWN,COLOR_BROWN,COLOR_DKBROWN,
  COLOR_DKBROWN,COLOR_BROWN,COLOR_BROWN,COLOR_DKBROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_DKBROWN,COLOR_BROWN,COLOR_BROWN,COLOR_DKBROWN,
  COLOR_DKBROWN,COLOR_BROWN,COLOR_BROWN,COLOR_DKBROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_DKBROWN,COLOR_BROWN,COLOR_BROWN,COLOR_DKBROWN,
  COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,
  COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_DKBROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_DKBROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,
  COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_DKBROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_DKBROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,
  COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_DKBROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_DKBROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,
  COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,
  COLOR_DKBROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_DKBROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_DKBROWN,
  COLOR_DKBROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_DKBROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_DKBROWN,
  COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,
};

// === STEEL WALL ===
static const UINT32 sprSteel[256] = {
  COLOR_GREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_GREY,
  COLOR_LTGREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_LTGREY,
  COLOR_LTGREY,COLOR_GREY,COLOR_LTGREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_LTGREY,COLOR_GREY,COLOR_LTGREY,
  COLOR_LTGREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_LTGREY,
  COLOR_LTGREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_LTGREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_LTGREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_LTGREY,
  COLOR_LTGREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_LTGREY,
  COLOR_LTGREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_LTGREY,
  COLOR_LTGREY,COLOR_GREY,COLOR_LTGREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_LTGREY,COLOR_GREY,COLOR_LTGREY,
  COLOR_LTGREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_LTGREY,
  COLOR_LTGREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_LTGREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_LTGREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_LTGREY,
  COLOR_LTGREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_LTGREY,
  COLOR_LTGREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_LTGREY,
  COLOR_LTGREY,COLOR_GREY,COLOR_LTGREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_LTGREY,COLOR_GREY,COLOR_LTGREY,
  COLOR_LTGREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_LTGREY,
  COLOR_LTGREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_GREY,COLOR_LTGREY,
  COLOR_GREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_LTGREY,COLOR_GREY,
};

// === WATER ===
static const UINT32 sprWater[256] = {
  COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,
  COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,
  COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,
  COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,
  COLOR_DKBLUE,COLOR_BLUE,COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,COLOR_BLUE,COLOR_DKBLUE,
  COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,COLOR_BLUE,COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,
  COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,
  COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,
  COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,
  COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,
  COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,
  COLOR_DKBLUE,COLOR_BLUE,COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,COLOR_BLUE,COLOR_DKBLUE,
  COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,COLOR_BLUE,COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,
  COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,
  COLOR_DKBLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_DKBLUE,
  COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,COLOR_DKBLUE,
};

// === TREE ===
static const UINT32 sprTree[256] = {
  0,COLOR_DKGREEN,0,0,0,COLOR_DKGREEN,0,COLOR_DKGREEN,COLOR_DKGREEN,0,COLOR_DKGREEN,0,0,0,COLOR_DKGREEN,0,
  COLOR_DKGREEN,COLOR_GREEN,COLOR_DKGREEN,0,COLOR_DKGREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_GREEN,COLOR_DKGREEN,0,COLOR_DKGREEN,COLOR_GREEN,COLOR_DKGREEN,
  0,COLOR_DKGREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_GREEN,COLOR_DKGREEN,0,
  0,0,COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,0,0,
  COLOR_DKGREEN,COLOR_DKGREEN,COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_DKGREEN,COLOR_DKGREEN,
  COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,
  COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,
  COLOR_DKGREEN,0,COLOR_DKGREEN,COLOR_DKGREEN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKGREEN,COLOR_DKGREEN,0,COLOR_DKGREEN,
  0,0,0,COLOR_DKGREEN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKGREEN,0,0,0,
  COLOR_DKGREEN,COLOR_DKGREEN,COLOR_DKGREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKGREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_DKGREEN,COLOR_DKGREEN,
  0,COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,0,
  0,0,COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,0,0,
  COLOR_DKGREEN,COLOR_DKGREEN,COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_DKGREEN,COLOR_DKGREEN,COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_DKGREEN,COLOR_DKGREEN,
  COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,
  0,COLOR_DKGREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_GREEN,COLOR_GREEN,COLOR_DKGREEN,COLOR_GREEN,COLOR_DKGREEN,0,
  0,0,COLOR_DKGREEN,0,0,COLOR_DKGREEN,0,COLOR_DKGREEN,COLOR_DKGREEN,0,COLOR_DKGREEN,0,0,COLOR_DKGREEN,0,0,
};

// === BASE (Eagle icon) ===
static const UINT32 sprBase[256] = {
  0,0,0,0,0,0,0,COLOR_GOLD,COLOR_GOLD,0,0,0,0,0,0,0,
  0,0,0,0,0,0,COLOR_GOLD,COLOR_DKGOLD,COLOR_DKGOLD,COLOR_GOLD,0,0,0,0,0,0,
  0,0,0,0,0,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,0,0,0,0,0,
  0,0,0,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_YELLOW,COLOR_YELLOW,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,0,0,0,
  0,0,COLOR_GOLD,COLOR_DKGOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_DKGOLD,COLOR_GOLD,0,0,
  0,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_YELLOW,COLOR_GOLD,COLOR_YELLOW,COLOR_YELLOW,COLOR_GOLD,COLOR_YELLOW,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,0,
  COLOR_GOLD,COLOR_DKGOLD,COLOR_GOLD,COLOR_YELLOW,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_YELLOW,COLOR_GOLD,COLOR_DKGOLD,COLOR_GOLD,
  COLOR_DKGOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_YELLOW,COLOR_YELLOW,COLOR_WHITE,COLOR_WHITE,COLOR_YELLOW,COLOR_YELLOW,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_DKGOLD,
  COLOR_DKGOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_YELLOW,COLOR_YELLOW,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_DKGOLD,
  0,COLOR_DKGOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_DKGOLD,0,
  0,0,COLOR_DKGOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_DKGOLD,0,0,
  0,0,0,COLOR_DKGOLD,COLOR_DKGOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_GOLD,COLOR_DKGOLD,COLOR_DKGOLD,0,0,0,
  0,0,0,COLOR_DKGOLD,COLOR_DKGOLD,COLOR_DKGOLD,COLOR_DKGOLD,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKGOLD,COLOR_DKGOLD,COLOR_DKGOLD,COLOR_DKGOLD,0,0,0,
  0,0,0,0,COLOR_DKGOLD,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKGOLD,0,0,0,0,
  0,0,0,0,0,COLOR_DKGOLD,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKBROWN,COLOR_DKGOLD,0,0,0,0,0,
  0,0,0,0,0,0,COLOR_DKGOLD,COLOR_DKGOLD,COLOR_DKGOLD,COLOR_DKGOLD,0,0,0,0,0,0,
};

// === SHIELD effect (circle) ===
static const UINT32 sprShield[256] = {
  0,0,0,0,0,COLOR_WHITE,COLOR_WHITE,COLOR_WHITE,COLOR_WHITE,COLOR_WHITE,COLOR_WHITE,0,0,0,0,0,
  0,0,0,COLOR_WHITE,COLOR_WHITE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_WHITE,COLOR_WHITE,0,0,0,
  0,0,COLOR_WHITE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_WHITE,0,0,
  0,COLOR_WHITE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_WHITE,0,
  0,COLOR_WHITE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_WHITE,0,
  COLOR_WHITE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_WHITE,
  COLOR_WHITE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_WHITE,
  COLOR_WHITE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_WHITE,
  COLOR_WHITE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_WHITE,
  COLOR_WHITE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_WHITE,
  COLOR_WHITE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_WHITE,
  0,COLOR_WHITE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_WHITE,0,
  0,COLOR_WHITE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_WHITE,0,
  0,0,COLOR_WHITE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_WHITE,0,0,
  0,0,0,COLOR_WHITE,COLOR_WHITE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_WHITE,COLOR_WHITE,0,0,0,
  0,0,0,0,0,COLOR_WHITE,COLOR_WHITE,COLOR_WHITE,COLOR_WHITE,COLOR_WHITE,COLOR_WHITE,0,0,0,0,0,
};

#endif
